apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name : saikiranbls        
  region: us-east-1          

iam:
  withOIDC: true               
  serviceAccounts:            
    - metadata:
        name: s3-access
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
